global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'fastapi'
    static_configs:
      - targets: ['app:8000']
    metrics_path: '/metrics'

rule_files:
  - '/etc/prometheus/rules/slo_rules.yaml'  # 🔥 Thêm rule SLO Alerting YAML (file ở thư mục rules/)
  #- '/etc/prometheus/rules/always_firing.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'